name: Publish Package to npmjs
on:
  push:
      # Pattern matched against refs/tags
      tags:
        - '*'           # Push events to every tag not containing /
env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish
